
export const EVENT_CUSTOMERSALE_PRODUCT_ADD = "EVENT_CUSTOMERSALE_PRODUCT_ADD";
export const EVENT_CUSTOMERSALE_PRODUCT_SUMMARY = "EVENT_CUSTOMERSALE_PRODUCT_SUMMARY";
export const EVENT_CUSTOMERSALE_CUSTOMER_DETAIL = "EVENT_CUSTOMERSALE_CUSTOMER_DETAIL";

